import { asyncHandler } from '../utils/asyncHandler.js';
import { ApiError } from '../utils/ApiError.js';
import { ApiResponse } from '../utils/ApiResponse.js';
import { db } from '../config/db.js';
import { eq } from 'drizzle-orm';
import { PAID_PLANS, USER_PLANS_CREDITS } from '../constants.js';
import { razorpay } from '../config/razorpay.config.js';
import { payments, type NewPayment } from '../db/schema/payments.js';
import Joi from 'joi';
import type { IErrorMessage, IRazorpayPaymentCapturedWebhook, PaidPlan } from '../types/types.js';
import crypto from 'crypto';
import { users } from '../db/schema/users.js';
import { creditTransactions, type NewCreditTransaction } from '../db/schema/creditTransactions.js';

// - Frontend
//   POST /payments/create-order
// - 'plan' sent in request body
// - Backend
//   Receives it and validate
// - If valid, Razorpay create Order
// - Backend stores payment data with Razorpay order data with status='created' in 'payments' table
const createRazorpayOrder = asyncHandler(async (req, res) => {
    // Auth check
    if(!req.user) {
        throw new ApiError(401, 'You need to be authenticated to start payment.');
    }

    const authUser = req.user;

    // Collect plan info from request body
    const { plan } = req.body as { plan: typeof PAID_PLANS[number] };

    // Validate if the plan is valid or not
    if(!plan || !PAID_PLANS.includes(plan)) {
        throw new ApiError(400, 'Invalid plan selected.');
    }

    // At this point, selected plan is valid, so calculate amount
    const amount = USER_PLANS_CREDITS[plan].price;

    // Create unique UUID string for storing receipt
    // razorpayOrderId -> generated by Razorpay
    // receipt -> generated by our backend
    // easier to trace the payment across database, Razorpay dashboard, etc.
    const receipt = crypto.randomUUID();

    // Create razorpay order, it will have status 'created' not 'paid'
    // We are just creating order (order intent)
    const razorpayOrder = await razorpay.orders.create({
        amount,
        currency: 'INR',
        receipt,
        notes: {
            userId: authUser.id,
            fullName: authUser.fullName,
            email: authUser.email,
            plan
        }
    });
    // returns something like:
    // {
    //     "id": "order_ABC",
    //     "amount": 21900,
    //     "currency": "INR",
    //     "status": "created",
    //     "receipt": "receipt_xyz"
    // }

    // Save the order in 'payments' table with status 'created'
    const paymentOrderData: NewPayment = {
        userId: authUser.id,
        plan,
        amount,
        razorpayOrderId: razorpayOrder.id,
        receipt,
        status: 'created'
    }

    const [createdPayment] = await db.insert(payments)
                                            .values(paymentOrderData)
                                            .returning({
                                                id: payments.id,
                                                plan: payments.plan,
                                                amount: payments.amount,
                                                razorpayOrderId: payments.razorpayOrderId
                                            });

    if(!createdPayment) {
        throw new ApiError(500, 'Unable to create Razorpay payment order.');
    }

    // Return response containing razorpay order id
    return res.status(201).json(
        new ApiResponse(
            201,
            { ...createdPayment, currency: razorpayOrder.currency },
            'Razorpay payment order created successfully.'
        )
    );
});

// - User clicks Purchase
// - Frontend -> Backend -> Razorpay Order created -> row added in 'payments' with status='created'
// - Backend sends order ID to Frontend
// - Frontend opens Razorpay Checkout popup using that order ID
// - User pays
// - Razorpay returns - payment_id, order_id, signature
// - Frontend sends those to backend
// - POST /verify-payment
// - Backend verifies signature
//      invalid -> reject
//      valid -> Updates DB, adds credits, updates plan in 'users'
const verifyRazorpayPayment = asyncHandler(async (req, res) => {
    // Auth check
    if(!req.user) {
        throw new ApiError(401, 'You need to be authenticated to verify this payment.');
    }

    const authUser = req.user;


    // Env variable protection
    if(!process.env.RAZORPAY_KEY_SECRET) {
        throw new ApiError(500, 'Razorpay credential is not configured properly.')
    }


    // Collect from request body
    const {
        razorpay_order_id,
        razorpay_payment_id,
        razorpay_signature
    } = req.body;


    // Validate incoming data
    const validatorSchema = Joi.object({
        razorpay_order_id: Joi.string()
                                .min(1)
                                .required()
                                .messages({
                                    'string.empty': 'razorpay_order_id is required.',
                                    'any.required': 'razorpay_order_id is required.',
                                    'string.min': 'razorpay_order_id must be at least 1 character.'
                                }),
        razorpay_payment_id: Joi.string()
                                .min(1)
                                .required()
                                .messages({
                                    'string.empty': 'razorpay_payment_id is required.',
                                    'any.required': 'razorpay_payment_id is required.',
                                    'string.min': 'razorpay_payment_id must be at least 1 character.'
                                }),
        razorpay_signature: Joi.string()
                                .min(1)
                                .required()
                                .messages({
                                    'string.empty': 'razorpay_signature is required.',
                                    'any.required': 'razorpay_signature is required.',
                                    'string.min': 'razorpay_signature must be at least 1 character.'
                                })
    });

    const { error } = validatorSchema.validate(
        { razorpay_order_id, razorpay_payment_id, razorpay_signature },
        { abortEarly: false }
    );

    let errorsObj: IErrorMessage = {};
    if(error) {
        error.details.forEach(detail => {
            errorsObj[detail.path[0] as string] = detail.message;
        });

        throw new ApiError(
            400,
            'Invalid or missing Razorpay payment data: razorpay_order_id, razorpay_payment_id, razorpay_signature.',
            errorsObj
        );
    }


    // Find the existing payment data (created during razorpay create order phase)
    const [payment] = await db.select()
                                .from(payments)
                                .where(eq(
                                    payments.razorpayOrderId, razorpay_order_id
                                ))
                                .limit(1);

    if(!payment) {
        throw new ApiError(404, 'Payment data not found.');
    }


    // Prevent duplicate verification
    // Without this, credits could be added twice
    if(payment.status === 'paid') {
        throw new ApiError(409, 'Payment already verified.');
    }


    // Generate the expected signature that Razorpay created internally using HMAC SHA256
    const expectedSignature = crypto.createHmac(
                                        'sha256', // hashing algorithm
                                        process.env.RAZORPAY_KEY_SECRET
                                    )
                                    .update(`${razorpay_order_id}|${razorpay_payment_id}`)
                                    .digest('hex');


    // Compare Razorpay given signature with our created one to verify
    if(!crypto.timingSafeEqual(Buffer.from(expectedSignature), Buffer.from(razorpay_signature))) {
        throw new ApiError(400, 'Payment signature verification failed.');
    }
    // Buffer.from(...) converts both signatures into Buffer objects
    // as crypto.timingSafeEqual() only works with Buffers
    // crypto.timingSafeEqual(a, b) compares every single character, even if first one is wrong
    // It always takes the exact same amount of time whether it's 100% wrong or 99% correct
    // So attackers can't learn anything from how fast/slow it responds


    // Store using transaction
    const purchasedCredits = USER_PLANS_CREDITS[payment.plan as PaidPlan].credits;

    await db.transaction(async (tx) => {
        // Update payment row
        await tx.update(payments)
                .set({
                    status: 'paid',
                    razorpayPaymentId: razorpay_payment_id,
                    razorpaySignature: razorpay_signature,
                    updatedAt: new Date()
                })
                .where(eq(payments.id, payment.id));

        // Get the latest credit balance
        // This allows us to increment from the current value rather than overwrite it
        const [currentUser] = await tx.select({ credit: users.credit })
                                        .from(users)
                                        .where(eq(users.id, authUser.id))
                                        .limit(1);
        if(!currentUser) {
            throw new ApiError(404, 'User not found for credit addition.');
        }
        await tx.update(users)
                .set({
                    credit: currentUser.credit + purchasedCredits,
                    plan: payment.plan,
                    updatedAt: new Date()
                })
                .where(eq(users.id, authUser.id));

        // Insert credit transaction
        const newCreditTransaction: NewCreditTransaction = {
            userId: authUser.id,
            credits: purchasedCredits,
            type: 'purchase',
            paymentId: payment.id,
        };
        await tx.insert(creditTransactions).values(newCreditTransaction);
    });


    // Return success plan
    return res.status(200).json(
        new ApiResponse(200, {}, 'Payment verified successfully.')
    );
});

// Frontend callbacks are unreliable. Browsers can close, lose internet, or users can tamper with
// requests. Webhooks are sent directly from Razorpay servers to our backend, making payment
// confirmation reliable.
// Webhook verification (POST /payments/webhook) can arrive before and after frontend verfication
// i.e. POST /payments/verify. Our backend should be able to handle both. This is called
// Idempotency.
const razorpayWebhook = asyncHandler(async (req, res) => {
    console.log('Razorpay webhook endpoint hit...');

    // Razorpay automatically sends a signature inside this header
    // This is generated using: Raw request body + our webhook secret
    // We will generate the same signature and compare them
    // If both signatures match, we know - it really came from Razorpay
    const razorpaySignature = req.headers['x-razorpay-signature'];

    if(!razorpaySignature || typeof razorpaySignature !== 'string') {
        throw new ApiError(400, 'Razorpay signature is missing.');
    }


    // req.body here is not a JS object. It is a Buffer (raw data) because this route will use:
    // express.raw({ type: 'application/json' })
    // We intentionally receive the original raw bytes.
    // Example:
    // Raw json data: {"event":"payment.captured"}
    // Now express.json() would convert it into
    // {
    //   event: "payment.captured"
    // }
    // Although both contain the same data, their raw bytes are different.
    // Here the representation got changed, this conversion changes the original bytes.
    // Razorpay generates the webhook signature using the original bytes. Thus signature could differ.
    // Therefore we must verify the signature before parsing JSON using raw data.
    const rawBody = req.body as Buffer;


    // Generate our signature
    const webhookSecret = process.env.RAZORPAY_WEBHOOK_SECRET;

    if(!webhookSecret) {
        throw new ApiError(500, 'RAZORPAY_WEBHOOK_SECRET is missing.');
    }

    const generatedSignature = crypto.createHmac('sha256', webhookSecret)
                                        .update(rawBody)
                                        .digest('hex');


    // Compare
    if(!crypto.timingSafeEqual(Buffer.from(generatedSignature), Buffer.from(razorpaySignature))) {
        throw new ApiError(400, 'Webhook signature verification failed.');
    }


    // Verified now, now parse JSON
    const webhookPayload: IRazorpayPaymentCapturedWebhook = JSON.parse(rawBody.toString('utf8'));


    // To only process payment captured (payment success) event,
    // ignore all others
    if(webhookPayload.event !== 'payment.captured') {
        return res.status(200).json(
            new ApiResponse(200, {}, 'Event ignored.')
        );
    }


    // Collect payment information
    const razorpayOrderId = webhookPayload.payload.payment.entity.order_id;
    const razorpayPaymentId = webhookPayload.payload.payment.entity.id;


    // Find our payment row
    const [payment] = await db.select()
                               .from(payments)
                               .where(eq(payments.razorpayOrderId, razorpayOrderId))
                               .limit(1);

    // Because Razorpay will retry every non-2xx response
    // If the order genuinely doesn't exist, we will receive retries for hours
    // So intentionally ignoring it, no retries
    if(!payment) {
        console.warn(`Webhook received for unknown order ${razorpayOrderId}`);
        return res.status(200).json(
            new ApiResponse(200, {}, 'Unknown payment ignored.')
        );
    }


    // Idempotency
    // Webhooks are not guaranteed to arrive only once.
    // Razorpay may retry the same webhook multiple times.
    // Therefore this endpoint must be idempotent.
    // If already the payment is processed, simply return success. Never give credits twice.
    // This way we can achieve Idempotency.
    if(payment.status === 'paid') {
        return res.status(200).json(
            new ApiResponse(200, {}, 'Payment already processed.')
        );
    }


    // Store using transaction
    const purchasedCredits = USER_PLANS_CREDITS[payment.plan as PaidPlan].credits;

    await db.transaction(async (tx) => {
        // Update payment row
        const [updatedPayment] = await tx.update(payments)
                                            .set({
                                                status: 'paid',
                                                razorpayPaymentId,
                                                razorpaySignature,
                                                updatedAt: new Date()
                                            })
                                            .where(eq(payments.id, payment.id))
                                            .returning({
                                                id: payments.id,
                                                userId: payments.userId
                                            });

        if(!updatedPayment) {
            throw new ApiError(500, 'Unable to update payment data.')
        }

        // Get the latest credit balance inside the transaction
        // This allows us to increment from the current value rather than overwrite it
        const [currentUser] = await tx.select({ credit: users.credit })
                                        .from(users)
                                        .where(eq(users.id, updatedPayment.userId))
                                        .limit(1);
        if(!currentUser) {
            throw new ApiError(404, 'User not found for credit addition.');
        }
        await tx.update(users)
                .set({
                    credit: currentUser.credit + purchasedCredits,
                    plan: payment.plan,
                    updatedAt: new Date()
                })
                .where(eq(users.id, updatedPayment.userId));
        // We intentionally read the latest credit inside the same transaction.
        // This prevents overwriting credits if another transaction updated the user
        // before this one committed.

        // Insert credit transaction
        const newCreditTransaction: NewCreditTransaction = {
            userId: updatedPayment.userId,
            credits: purchasedCredits,
            type: 'purchase',
            paymentId: payment.id
        };
        await tx.insert(creditTransactions).values(newCreditTransaction);
    });


    // Return success plan
    return res.status(200).json(
        new ApiResponse(200, {}, 'Payment verified successfully.')
    );
});

export { createRazorpayOrder, verifyRazorpayPayment, razorpayWebhook };
