import { asyncHandler } from '../utils/asyncHandler.js';
import { ApiError } from '../utils/ApiError.js';
import { ApiResponse } from '../utils/ApiResponse.js';
import { db } from '../config/db.js';
import { eq } from 'drizzle-orm';
import { PAID_PLANS, USER_PLANS_CREDITS } from '../constants.js';
import { razorpay } from '../config/razorpay.config.js';
import { payments, type NewPayment } from '../db/schema/payments.js';

// - Frontend
//   POST /payments/create-order
// - 'plan' sent in request body
// - Backend
//   Receives it and validate
// - If valid, Razorpay create Order
// - Backend stores payment data with Razorpay order data with status='created' in 'payments' table
const createRazorpayOrder = asyncHandler(async (req, res) => {
    // Auth check
    if(!req.user) {
        throw new ApiError(401, 'You need to be authenticated to start payment.');
    }

    const authUser = req.user;

    // Collect plan info from request body
    const { plan } = req.body as { plan: typeof PAID_PLANS[number] };

    // Validate if the plan is valid or not
    if(!plan || !PAID_PLANS.includes(plan)) {
        throw new ApiError(400, 'Invalid plan selected.');
    }

    // At this point, selected plan is valid, so calculate amount
    const amount = USER_PLANS_CREDITS[plan].price;

    // Create unique UUID string for storing receipt
    // razorpayOrderId -> generated by Razorpay
    // receipt -> generated by our backend
    // easier to trace the payment across database, Razorpay dashboard, etc.
    const receipt = crypto.randomUUID();

    // Create razorpay order, it will have status 'created' not 'paid'
    // We are just creating order (order intent)
    const razorpayOrder = await razorpay.orders.create({
        amount,
        currency: 'INR',
        receipt,
        notes: {
            userId: authUser.id,
            fullName: authUser.fullName,
            email: authUser.email,
            plan
        }
    });
    // returns something like:
    // {
    //     "id": "order_ABC",
    //     "amount": 21900,
    //     "currency": "INR",
    //     "status": "created",
    //     "receipt": "receipt_xyz"
    // }

    // Save the order in 'payments' table with status 'created'
    const paymentOrderData: NewPayment = {
        userId: authUser.id,
        plan,
        amount,
        razorpayOrderId: razorpayOrder.id,
        receipt,
        status: 'created'
    }

    const [createdPayment] = await db.insert(payments)
                                            .values(paymentOrderData)
                                            .returning({
                                                id: payments.id,
                                                plan: payments.plan,
                                                amount: payments.amount,
                                                razorpayOrderId: payments.razorpayOrderId
                                            });

    if(!createdPayment) {
        throw new ApiError(500, 'Unable to create Razorpay payment order.');
    }

    // Return response containing razorpay order id
    return res.status(201).json(
        new ApiResponse(
            201,
            { ...createdPayment, currency: razorpayOrder.currency },
            'Razorpay payment order created successfully.'
        )
    );
});

// - User clicks Purchase
// - Frontend -> Backend -> Razorpay Order created -> row added in 'payments' with status='created'
// - Backend sends order ID to Frontend
// - Frontend opens Razorpay Checkout popup
// - User pays
// - Razorpay returns - payment_id, order_id, signature
// - Frontend sends those to backend
// - POST /verify-payment
// - Backend verifies signature
//      invalid -> reject
//      valid -> Updates DB, adds credits, updates plan in 'users'
export { createRazorpayOrder };
